service: image-resize

frameworkVersion: '2 || 3'

custom:
  # bucket: ${ssm:/database/testdb/endpoint~true}
  bucket: aws-bucket-hhassen-2022mars

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  memorySize: 128
  timeout: 10
  stage: ${opt:stage, "dev"}
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:PutObjectAcl
          Resource: "arn:aws:s3:::${self:custom.bucket}/*"
  # add x-ray tracing
  tracing:
    apiGateway: true
    lambda: true

functions:
  imageResize:
    handler: app.lambdaHandler
    events:
      - http:
          path: image
          method: post
    environment:
      S3_BUCKET: ${self:custom.bucket}